[tox]
skipsdist = True
envlist = molecule

[testenv]
deps =
  -r tox-requirements.txt
  ansible-core>=2.11,<2.12

commands_pre =
  ansible-galaxy collection install -f {toxinidir}/molecule/_vendor/collections/containers-podman-1.19.0.tar.gz
  ansible-galaxy collection install -f {toxinidir}/molecule/_vendor/collections/ansible-posix-2.1.0.tar.gz
commands =
  molecule test -s podman --destroy=never
  molecule converge -s podman
  molecule verify -s podman
  molecule destroy -s podman
passenv = *
